# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2Sf7Cw6Lb9ArCfMnk4oxm2Lf9bXpxhU
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

st.set_page_config(page_title="Ecosistema Gamer LATAM", layout="wide")

# --- Título y descripción ---
st.title("📊 Ecosistema de Videojuegos en Latinoamérica")
st.markdown("""
Esta plataforma presenta un análisis exploratorio sobre juegos desarrollados en Latinoamérica.
Se muestran estadísticas, limpieza de datos y visualizaciones de ventas por país, año y juego.
""")

# --- Cargar datos ---
@st.cache_data
def cargar_datos():
    return pd.read_csv("ecosistema_videojuegos_latam.csv")

df = cargar_datos()

# --- Sección 1: Vista previa y limpieza ---
st.header("🧹 Limpieza de Datos")

col1, col2 = st.columns(2)
with col1:
    st.write("**Duplicados:**", df.duplicated().sum())
    st.write("**Nulos por columna:**")
    st.write(df.isnull().sum())

with col2:
    df_clean = df.drop_duplicates().dropna()
    st.success(f"Registros limpios: {len(df_clean)}")

# --- Sección 2: Estadísticas básicas ---
st.header("📈 Estadísticas Generales")
col3, col4, col5 = st.columns(3)

with col3:
    st.metric("🎮 Juegos únicos", df_clean["juego"].nunique())
with col4:
    st.metric("📦 Total ventas", f"{df_clean['ventas'].sum():,}")
with col5:
    st.metric("💰 Promedio ventas", f"{df_clean['ventas'].mean():,.0f}")

# --- Sección 3: Gráficos ---
st.header("📊 Visualizaciones")

# Ventas por país
st.subheader("Ventas totales por país")
fig1, ax1 = plt.subplots(figsize=(10, 5))
sns.barplot(data=df_clean, x="pais", y="ventas", estimator=sum, ci=None, ax=ax1)
plt.xticks(rotation=45)
st.pyplot(fig1)

# Ventas por año
st.subheader("Distribución de ventas por año")
fig2, ax2 = plt.subplots(figsize=(10, 5))
sns.boxplot(data=df_clean, x="anio", y="ventas", ax=ax2)
st.pyplot(fig2)

# Top juegos más vendidos
st.subheader("Top 10 Juegos más vendidos")
top_juegos = df_clean.groupby("juego")["ventas"].sum().sort_values(ascending=False).head(10)
fig3, ax3 = plt.subplots(figsize=(10, 6))
sns.barplot(x=top_juegos.values, y=top_juegos.index, ax=ax3)
st.pyplot(fig3)

# --- Sección 4: Riesgos y seguridad ---
st.header("🔒 Riesgos y Seguridad de Datos")

st.markdown("""
- Evita publicar archivos con datos sensibles de usuarios o empresas sin su autorización.
- Verifica la fuente y calidad de los datos cargados.
- Aplica medidas de cifrado si trabajas con datos privados en producción.
- Asegura autenticación si despliegas esta app en línea.
""")